# Generated by Django 4.1.5 on 2023-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_status_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
